package cucumber.framework.scenariotest.jcadmin;

public enum JCAdminTesting {
	M001("Admin login dan membuka halaman testimonials"),
	M002("Admin klik tombol edit testimonial pertama"),
	M003("Admin invalid login input username"),
	M004("Admin valid login input password"),
	M005("Admin invalid login input password uppercase"),
	M006("Admin invalid login upper"),
	M007("Admin invalid login input spasi"),
	M008("Admin invalid login user tanpa format email"),
	MOO9("Menambah daftar testimonial active"),
	MOO10("Menambah daftar testimonial noactive"),
	MOO11("Menambah daftar testimonial active rating 0-5"),
	MOO12("Menambah daftar testimonial no active rating 0-5"),
	MOO13("Menambah daftar testimonial no active rating "), 
	MOO14("Menambah daftar testimonial no active rating "), 
	MOO15("Menambah daftar testimonial no active rating "), 
	MOO16("Menambah daftar testimonial no active rating "), 
	MOO17("Menambah daftar testimonial no active rating "), 
	MOO18("Menambah daftar testimonial no active rating "), 
	MOO19("Menambah daftar testimonial no active rating "), 
	MOO20("Menambah daftar testimonial no active rating "), 
	MOO21("Menambah daftar testimonial no active rating "), 
	MOO22("Menambah daftar testimonial no active rating "), 
	MOO23("Menambah daftar testimonial no active rating "), 
	MOO24("Menambah daftar testimonial no active rating "), 
	MOO25("Menambah daftar testimonial no active rating "), 
	MOO26("Menambah daftar testimonial no active rating "), 
	MOO27("Menambah daftar testimonial no active rating "), 
	MOO28("Menambah daftar testimonial no active rating "), 
	MOO29("Menambah daftar testimonial no active rating "), 
	MOO30("Menambah daftar testimonial no active rating "), 
	MOO31("Menambah daftar testimonial no active rating "), 
	MOO32("Menambah daftar testimonial no active rating "), 
	MOO33("Menambah daftar testimonial no active rating "), 
	MOO34("Menambah daftar testimonial no active rating "), 
	MOO35("Menambah daftar testimonial no active rating "), 
	MOO36("Menambah daftar testimonial no active rating "), 
	MOO37("Menambah daftar testimonial no active rating "), 
	MOO38("Menambah daftar testimonial no active rating "), 
	MOO39("Menambah daftar testimonial no active rating "), 
	MOO40("Menambah daftar testimonial no active rating "), 
	MOO41("Menambah daftar testimonial no active rating "), 
	MOO42("Menambah daftar testimonial no active rating "), 
	MOO43("Menambah daftar testimonial no active rating "), 
	MOO44("Menambah daftar testimonial no active rating "), 
	MOO45("Menambah daftar testimonial no active rating "), 
	MOO46("Menambah daftar testimonial no active rating "), 
	MOO47("Menambah daftar testimonial no active rating "), 
	MOO48("Menambah daftar testimonial no active rating "), 
	MOO49("Menambah daftar testimonial no active rating "),
	MOO50("Menambah daftar testimonial no active rating "),
	MOO51("Menambah daftar testimonial no active rating "), 
	MOO52("Menambah daftar testimonial no active rating "), 
	MOO53("Menambah daftar testimonial no active rating "), 
	MOO54("Menambah daftar testimonial no active rating "), 
	MOO55("Menambah daftar testimonial no active rating "), 
	MOO56("Menambah daftar testimonial no active rating "), 
	MOO57("Menambah daftar testimonial no active rating "), 
	MOO58("Menambah daftar testimonial no active rating "), 
	MOO59("Menambah daftar testimonial no active rating "), 
	MOO60("Menambah daftar testimonial no active rating "), 
	MOO61("Menambah daftar testimonial no active rating "), 
	MOO62("Menambah daftar testimonial no active rating "), 
	MOO63("Menambah daftar testimonial no active rating "), 
	MOO64("Menambah daftar testimonial no active rating "), 
	MOO65("Menambah daftar testimonial no active rating "), 
	MOO66("Menambah daftar testimonial no active rating "), 
	MOO67("Menambah daftar testimonial no active rating "), 
	MOO68("Menambah daftar testimonial no active rating "), 
	MOO69("Menambah daftar testimonial no active rating "), 
	MOO70("Menambah daftar testimonial no active rating "), 
	MOO71("Menambah daftar testimonial no active rating "), 
	MOO72("Menambah daftar testimonial no active rating "), 
	MOO73("Menambah daftar testimonial no active rating "), 
	MOO74("Menambah daftar testimonial no active rating "), 
	MOO75("Menambah daftar testimonial no active rating "), 
	MOO76("Menambah daftar testimonial no active rating "), 
	MOO77("Menambah daftar testimonial no active rating "), 
	MOO78("Menambah daftar testimonial no active rating "), 
	MOO79("Menambah daftar testimonial no active rating "), 
	MOO80("Menambah daftar testimonial no active rating "), 
	MOO81("Menambah daftar testimonial no active rating "), 
	MOO82("Menambah daftar testimonial no active rating "), 
	MOO83("Menambah daftar testimonial no active rating "), 
	MOO84("Menambah daftar testimonial no active rating "), 
	MOO85("Menambah daftar testimonial no active rating "), 
	MOO86("Menambah daftar testimonial no active rating "), 
	MOO87("Menambah daftar testimonial no active rating "), 
	MOO88("Menambah daftar testimonial no active rating "), 
	MOO89("Menambah daftar testimonial no active rating "), 
	MOO90("Menambah daftar testimonial no active rating "), 
	MOO91("Menambah daftar testimonial no active rating "), 
	MOO92("Menambah daftar testimonial no active rating "), 
	MOO93("Menambah daftar testimonial no active rating "), 
	MOO94("Menambah daftar testimonial no active rating "), 
	MOO95("Menambah daftar testimonial no active rating "), 
	MOO96("Menambah daftar testimonial no active rating "), 
	MOO97("Menambah daftar testimonial no active rating "), 
	MOO98("Menambah daftar testimonial no active rating "), 
	MOO99("Menambah daftar testimonial no active rating "), 
	MOO100("Menambah daftar testimonial no active rating "), 
	MOO101("Menambah daftar testimonial no active rating "), 
	MOO102("Menambah daftar testimonial no active rating "), 
	MOO103("Menambah daftar testimonial no active rating "), 
	MOO104("Menambah daftar testimonial no active rating "), 
	MOO105("Menambah daftar testimonial no active rating "), 
	MOO106("Menambah daftar testimonial no active rating "), 
	MOO107("Menambah daftar testimonial no active rating "), 
	MOO108("Menambah daftar testimonial no active rating "), 
	MOO109("Menambah daftar testimonial no active rating "), 
	MOO110("Menambah daftar testimonial no active rating "), 
	MOO111("Menambah daftar testimonial no active rating "), 
	MOO112("Menambah daftar testimonial no active rating "), 
	MOO113("Menambah daftar testimonial no active rating "), 
	MOO114("Menambah daftar testimonial no active rating "), 
	MOO115("Menambah daftar testimonial no active rating "), 
	MOO116("Menambah daftar testimonial no active rating "), 
	MOO117("Menambah daftar testimonial no active rating "), 
	MOO118("Menambah daftar testimonial no active rating "), 
	MOO119("Menambah daftar testimonial no active rating "), 
	MOO120("Menambah daftar testimonial no active rating "), 
	MOO121("Menambah daftar testimonial no active rating "), 
	MOO122("Menambah daftar testimonial no active rating "), 
	MOO123("Menambah daftar testimonial no active rating "), 
	MOO124("Menambah daftar testimonial no active rating "), 
	MOO125("Menambah daftar testimonial no active rating "), 
	MOO126("Menambah daftar testimonial no active rating "), 
	MOO127("Menambah daftar testimonial no active rating "), 
	MOO128("Menambah daftar testimonial no active rating "), 
	MOO129("Menambah daftar testimonial no active rating "), 
	MOO130("Menambah daftar testimonial no active rating "), 
	MOO131("Menambah daftar testimonial no active rating "), 
	MOO132("Menambah daftar testimonial no active rating "), 
	MOO133("Menambah daftar testimonial no active rating "), 
	MOO134("Menambah daftar testimonial no active rating "), 
	MOO135("Menambah daftar testimonial no active rating "), 
	MOO136("Menambah daftar testimonial no active rating "), 
	MOO137("Menambah daftar testimonial no active rating "), 
	MOO138("Menambah daftar testimonial no active rating "), 
	MOO139("Menambah daftar testimonial no active rating "), 
	MOO140("Menambah daftar testimonial no active rating "), 
	MOO141("Menambah daftar testimonial no active rating "), 
	MOO142("Menambah daftar testimonial no active rating "), 
	MOO143("Menambah daftar testimonial no active rating "), 
	MOO144("Menambah daftar testimonial no active rating "), 
	MOO145("Menambah daftar testimonial no active rating "), 
	MOO146("Menambah daftar testimonial no active rating "), 
	MOO147("Menambah daftar testimonial no active rating "), 
	MOO148("Menambah daftar testimonial no active rating "), 
	MOO149("Menambah daftar testimonial no active rating "),
	MOO150("Menambah daftar testimonial no active rating "), 
	MOO151("Menambah daftar testimonial no active rating "), 
	MOO152("Menambah daftar testimonial no active rating "), 
	MOO153("Menambah daftar testimonial no active rating "), 
	MOO154("Menambah daftar testimonial no active rating "), 
	MOO155("Menambah daftar testimonial no active rating "), 
	MOO156("Menambah daftar testimonial no active rating "), 
	MOO157("Menambah daftar testimonial no active rating "), 
	MOO158("Menambah daftar testimonial no active rating "), 
	MOO159("Menambah daftar testimonial no active rating "), 
	MOO160("Menambah daftar testimonial no active rating "), 
	MOO161("Menambah daftar testimonial no active rating "), 
	MOO162("Menambah daftar testimonial no active rating "), 
	MOO163("Menambah daftar testimonial no active rating "), 
	MOO164("Menambah daftar testimonial no active rating "), 
	MOO165("Menambah daftar testimonial no active rating "), 
	MOO166("Menambah daftar testimonial no active rating "), 
	MOO167("Menambah daftar testimonial no active rating "), 
	MOO168("Menambah daftar testimonial no active rating "), 
	MOO169("Menambah daftar testimonial no active rating ");
	
	private String testName;
	
	private JCAdminTesting(String value) {
		testName = value;
	}
	
	public String getTestName() {
		return testName;
	}
}
